In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('train_binary.csv')

In [3]:
df.describe()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,label
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,500.646426,0.499961,5001.475347,99.663713,0.005001,50004.809044,475.641138,0.459966,4401.601767,84.672616,...,74.912848,0.999289,2495.055679,115.182153,0.591371,2056.161274,1.277149,0.003311,-0.002680,0.303600
std,102.167451,0.010176,1018.686318,50.946605,0.001021,10193.068407,97.407907,0.009576,899.975387,44.935452,...,25.024744,0.100383,498.380114,27.473200,0.159825,418.518026,0.666971,1.042740,1.000006,0.459817
min,44.552292,0.462030,966.650179,-130.775155,0.000618,6888.787646,37.323957,0.421474,877.269883,-106.825468,...,-20.047149,0.540305,476.137094,41.911967,0.156876,729.555101,0.008627,-9.263822,-1.000000,0.000000
25%,431.558647,0.493091,4313.706744,65.277365,0.004320,43098.759523,409.719004,0.453495,3794.988088,54.217184,...,57.922540,0.932153,2156.137582,94.564638,0.471014,1686.072685,0.775074,-0.375392,-1.000000,0.000000
50%,500.723423,0.499944,5000.138426,99.838686,0.005002,50049.357109,475.743828,0.459978,4403.108013,84.700557,...,74.865170,0.999356,2497.297022,108.480117,0.546799,2181.189715,1.203037,0.000198,-1.000000,0.000000
75%,570.043673,0.506870,5686.792287,134.056839,0.005688,56864.960088,541.822674,0.466470,5008.693250,115.092937,...,91.921637,1.066220,2832.091910,136.839835,0.728151,2371.657805,1.692574,0.380763,1.000000,1.000000
max,930.857578,0.541910,9061.589352,332.284250,0.008894,95723.410815,882.181943,0.498576,8043.777043,272.166998,...,174.186524,1.461638,4572.047464,208.654969,1.167666,3058.142671,4.946865,9.609629,1.000000,1.000000

In [4]:
labels = df.label

In [5]:
df = df.drop('label',axis = 1)

In [6]:
metric = pd.DataFrame({'label' : df.columns,
              'mean' : np.mean(df,axis =0),
              'std' : np.std(df,axis = 0)})

In [7]:
for col in df.columns:
  df[col] = (df[col] - np.mean(df[col]))/np.std(df[col])

In [8]:
for col in df.columns:
  labels = labels[np.abs(df[col]) < 3.0]
  df = df[np.abs(df[col]) < 3.0]

In [11]:
class LogisticRegression:
    def __init__(self):
        self.optimizer = None
        self.hat_m_b = None
        self.hat_m_w = None
        self.r_v_b = None
        self.r_v_w = None
        self.hat_v_w = None
        self.hat_v_b = None
        self.x = None
        self.y = None
        self._y = None
        self.w = None
        self.b = None
        self.w_error = None
        self.b_error = None
        self.m_w = None
        self.m_b = None
        self.v_w = None
        self.v_b = None
        self.epoch_count = 1
        self.epoch_limit = None
    def predict(self,x):
        out = 1/(1 + np.exp(-(np.dot(x , self.w) + self.b)))
        return out
    def fit(self,x,y,epochs = 100,optimizer = 'gd'):
        self.x = x
        self.y = y
        self.w = np.zeros(x.shape[1])
        self.b = 0
        self._y = self.predict(self.x)
        self.epoch_limit = epochs
        self.optimizer = optimizer
        #initialized the momentum to avoid type error in first iteration
        self.v_w = np.zeros(self.x.shape[1])
        self.m_w = np.zeros(self.x.shape[1])
        self.m_b = 0
        self.v_b = 0
        #####
        self.b_error = -(np.mean(self.y - self._y))
        self.w_error = -(np.dot(self.x.transpose(),self.y - self._y))/self.x.shape[0]
        if self.optimizer == "adam":
            update_step = self.adam
        elif self.optimizer == "RMSprop":
            update_step = self.RMSprop
        elif self.optimizer == "momentum":
            update_step = self.momentum
        elif self.optimizer == "gd":
            update_step = self.gd
        else:
            raise ValueError(f"Unknown optimizer: {self.optimizer}")
        while self.epoch_count <= self.epoch_limit:
            self._y = self.predict(self.x)
            self.loss = sum([-t_hat*np.log(t) - (1-t_hat)*np.log(1-t) for t , t_hat in zip(self._y,self.y)])/len(self.y)
            self.b_error = -(np.mean(self.y - self._y))
            self.w_error = -(np.dot(self.x.transpose(),self.y - self._y))/self.x.shape[0]
            update_step()
            print(f'Epoch : {self.epoch_count} Loss : {self.loss}')
            self.epoch_count += 1
    def adam(self, beta1 = 0.9 , beta2 = 0.999 ,epsilon = 10**-8,gamma = 0.0003):
        #momentum variables
        self.m_w = beta1*self.m_w + (1 - beta1)*self.w_error
        self.m_b = beta1*self.m_b + (1 - beta1)*self.b_error
        #RMSpropFactors
        self.v_w = beta2*self.v_w + (1-beta2)*(self.w_error**2)
        self.v_b = beta2*self.v_b + (1-beta2)*(self.b_error**2)
        #bias correcting the variance values
        self.hat_v_w = self.v_w / (1 - beta2**self.epoch_count)
        self.hat_v_b = self.v_b / (1 - beta2**self.epoch_count)
        #RMSpropFactvectors for updating the final values
        self.r_v_w = 1 / (np.sqrt(self.hat_v_w + epsilon))
        self.r_v_b = 1 / (np.sqrt(self.hat_v_b + epsilon))
        #bias correcting the momentum values
        self.hat_m_w = self.m_w / (1 - beta1**self.epoch_count)
        self.hat_m_b = self.m_b / (1 - beta1**self.epoch_count)
        #Updating the final value
        self.b = self.b - self.hat_m_b*self.r_v_b*gamma
        self.w = self.w - np.multiply(self.hat_m_w,self.r_v_w)*gamma
    def RMSprop(self,beta2 = 0.999,epsilon = 10**-8, gamma = 0.001):
        self.v_w = beta2*self.v_w + (1-beta2)*(self.w_error**2)
        self.v_b = beta2*self.v_b + (1-beta2)*(self.b_error**2)
        self.r_v_w = 1 / (np.sqrt(self.v_w + epsilon))
        self.r_v_b = 1 / (np.sqrt(self.v_b + epsilon))
        self.b = self.b - self.b_error*self.r_v_b*gamma
        self.w = self.w - np.multiply(self.w_error,self.r_v_w)*gamma
    def momentum(self,beta1 = 0.9 , gamma = 0.001):
        self.m_w = beta1*self.m_w + (1 - beta1)*self.w_error
        self.m_b = beta1*self.m_b + (1 - beta1)*self.b_error
        self.b = self.b - self.m_b*gamma
        self.w = self.w - self.m_w*gamma
    def gd(self,gamma = 0.005):
        self.w = self.w - gamma*self.w_error
        self.b = self.b - self.b_error*gamma

In [12]:
model = LogisticRegression()
model.fit(df.to_numpy(),labels,optimizer='gd',epochs=1000)

Epoch : 1 Loss : 0.6931471805592173
Epoch : 2 Loss : 0.6894688818834972
Epoch : 3 Loss : 0.6858247904203757
Epoch : 4 Loss : 0.6822145683096862
Epoch : 5 Loss : 0.6786378790661879
Epoch : 6 Loss : 0.6750943876614064
Epoch : 7 Loss : 0.6715837606016037
Epoch : 8 Loss : 0.6681056660024806
Epoch : 9 Loss : 0.6646597736606537
Epoch : 10 Loss : 0.6612457551221232
Epoch : 11 Loss : 0.6578632837475655
Epoch : 12 Loss : 0.6545120347745965
Epoch : 13 Loss : 0.6511916853770238
Epoch : 14 Loss : 0.6479019147212202
Epoch : 15 Loss : 0.6446424040195001
Epoch : 16 Loss : 0.6414128365807392
Epoch : 17 Loss : 0.6382128978581596
Epoch : 18 Loss : 0.635042275494401
Epoch : 19 Loss : 0.6319006593639129
Epoch : 20 Loss : 0.6287877416127863
Epoch : 21 Loss : 0.6257032166959546
Epoch : 22 Loss : 0.6226467814119533
Epoch : 23 Loss : 0.6196181349352438
Epoch : 24 Loss : 0.6166169788462117
Epoch : 25 Loss : 0.6136430171587948
Epoch : 26 Loss : 0.6106959563459038
Epoch : 27 Loss : 0.607775505362713
Epoch : 28 Loss : 0.604881375667751
Epoch : 29 Loss : 0.6020132812420771
Epoch : 30 Loss : 0.5991709386063028
Epoch : 31 Loss : 0.5963540668358326
Epoch : 32 Loss : 0.5935623875741945
Epoch : 33 Loss : 0.5907956250445614
Epoch : 34 Loss : 0.5880535060595847
Epoch : 35 Loss : 0.5853357600294522
Epoch : 36 Loss : 0.5826421189684633
Epoch : 37 Loss : 0.5799723174999469
Epoch : 38 Loss : 0.5773260928597453
Epoch : 39 Loss : 0.5747031848981828
Epoch : 40 Loss : 0.572103336080723
Epoch : 41 Loss : 0.5695262914872758
Epoch : 42 Loss : 0.5669717988102113
Epoch : 43 Loss : 0.5644396083511163
Epoch : 44 Loss : 0.5619294730165254
Epoch : 45 Loss : 0.5594411483123356
Epoch : 46 Loss : 0.5569743923373085
Epoch : 47 Loss : 0.5545289657754501
Epoch : 48 Loss : 0.5521046318874923
Epoch : 49 Loss : 0.5497011565014125
Epoch : 50 Loss : 0.5473183080020447
Epoch : 51 Loss : 0.544955857319912
Epoch : 52 Loss : 0.5426135779192218
Epoch : 53 Loss : 0.5402912457851151
Epoch : 54 Loss : 0.5379886394102289
Epoch : 55 Loss : 0.5357055397805254
Epoch : 56 Loss : 0.5334417303605564
Epoch : 57 Loss : 0.5311969970780575
Epoch : 58 Loss : 0.5289711283080727
Epoch : 59 Loss : 0.5267639148564419
Epoch : 60 Loss : 0.5245751499428633
Epoch : 61 Loss : 0.5224046291834753
Epoch : 62 Loss : 0.5202521505729956
Epoch : 63 Loss : 0.5181175144664826
Epoch : 64 Loss : 0.5160005235607005
Epoch : 65 Loss : 0.5139009828751437
Epoch : 66 Loss : 0.5118186997327538
Epoch : 67 Loss : 0.5097534837403483
Epoch : 68 Loss : 0.5077051467687428
Epoch : 69 Loss : 0.5056735029327051
Epoch : 70 Loss : 0.5036583685706136
Epoch : 71 Loss : 0.5016595622239663
Epoch : 72 Loss : 0.4996769046166813
Epoch : 73 Loss : 0.4977102186342838
Epoch : 74 Loss : 0.4957593293028997
Epoch : 75 Loss : 0.49382406376821786
Epoch : 76 Loss : 0.4919042512742272
Epoch : 77 Loss : 0.4899997231420198
Epoch : 78 Loss : 0.48811031274839917
Epoch : 79 Loss : 0.486235855504506
Epoch : 80 Loss : 0.48437618883442096
Epoch : 81 Loss : 0.4825311521536805
Epoch : 82 Loss : 0.48070058684787387
Epoch : 83 Loss : 0.4788843362511407
Epoch : 84 Loss : 0.4770822456248172
Epoch : 85 Loss : 0.4752941621359833
Epoch : 86 Loss : 0.47351993483610744
Epoch : 87 Loss : 0.471759414639809
Epoch : 88 Loss : 0.47001245430351973
Epoch : 89 Loss : 0.4682789084044054
Epoch : 90 Loss : 0.4665586333192045
Epoch : 91 Loss : 0.46485148720328356
Epoch : 92 Loss : 0.4631573299696832
Epoch : 93 Loss : 0.4614760232683476
Epoch : 94 Loss : 0.4598074304654223
Epoch : 95 Loss : 0.4581514166226802
Epoch : 96 Loss : 0.4565078484770844
Epoch : 97 Loss : 0.4548765944204489
Epoch : 98 Loss : 0.4532575244792827
Epoch : 99 Loss : 0.45165051029470565
Epoch : 100 Loss : 0.45005542510260327
Epoch : 101 Loss : 0.44847214371382377
Epoch : 102 Loss : 0.4469005424946219
Epoch : 103 Loss : 0.4453404993471972
Epoch : 104 Loss : 0.44379189369043026
Epoch : 105 Loss : 0.4422546064407726
Epoch : 106 Loss : 0.440728519993257
Epoch : 107 Loss : 0.43921351820279547
Epoch : 108 Loss : 0.4377094863655225
Epoch : 109 Loss : 0.4362163112003599
Epoch : 110 Loss : 0.4347338808307989
Epoch : 111 Loss : 0.43326208476678646
Epoch : 112 Loss : 0.4318008138868503
Epoch : 113 Loss : 0.43034996042039064
Epoch : 114 Loss : 0.4289094179301084
Epoch : 115 Loss : 0.42747908129469026
Epoch : 116 Loss : 0.4260588466916318
Epoch : 117 Loss : 0.4246486115802443
Epoch : 118 Loss : 0.42324827468486387
Epoch : 119 Loss : 0.42185773597823156
Epoch : 120 Loss : 0.42047689666508037
Epoch : 121 Loss : 0.4191056591658916
Epoch : 122 Loss : 0.4177439271008142
Epoch : 123 Loss : 0.4163916052738094
Epoch : 124 Loss : 0.4150485996569701
Epoch : 125 Loss : 0.41371481737502985
Epoch : 126 Loss : 0.4123901666899972
Epoch : 127 Loss : 0.4110745569860794
Epoch : 128 Loss : 0.4097678987547075
Epoch : 129 Loss : 0.40847010357974156
Epoch : 130 Loss : 0.40718108412292636
Epoch : 131 Loss : 0.4059007541094698
Epoch : 132 Loss : 0.40462902831380015
Epoch : 133 Loss : 0.40336582254553993
Epoch : 134 Loss : 0.4021110536356202
Epoch : 135 Loss : 0.4008646394225786
Epoch : 136 Loss : 0.39962649873906453
Epoch : 137 Loss : 0.3983965513984733
Epoch : 138 Loss : 0.3971747181817767
Epoch : 139 Loss : 0.39596092082450346
Epoch : 140 Loss : 0.39475508200396453
Epoch : 141 Loss : 0.3935571253265078
Epoch : 142 Loss : 0.3923669753150826
Epoch : 143 Loss : 0.3911845573968863
Epoch : 144 Loss : 0.39000979789117846
Epoch : 145 Loss : 0.388842623997312
Epoch : 146 Loss : 0.38768296378287054
Epoch : 147 Loss : 0.38653074617197475
Epoch : 148 Loss : 0.38538590093375896
Epoch : 149 Loss : 0.3842483586710151
Epoch : 150 Loss : 0.38311805080896305
Epoch : 151 Loss : 0.38199490958419124
Epoch : 152 Loss : 0.3808788680337309
Epoch : 153 Loss : 0.3797698599843202
Epoch : 154 Loss : 0.3786678200417617
Epoch : 155 Loss : 0.3775726835804798
Epoch : 156 Loss : 0.3764843867331778
Epoch : 157 Loss : 0.3754028663806567
Epoch : 158 Loss : 0.3743280601417957
Epoch : 159 Loss : 0.37325990636363615
Epoch : 160 Loss : 0.37219834411162006
Epoch : 161 Loss : 0.3711433131599766
Epoch : 162 Loss : 0.3700947539822111
Epoch : 163 Loss : 0.36905260774178267
Epoch : 164 Loss : 0.3680168162828292
Epoch : 165 Loss : 0.36698732212112467
Epoch : 166 Loss : 0.3659640684350682
Epoch : 167 Loss : 0.36494699905686395
Epoch : 168 Loss : 0.3639360584638077
Epoch : 169 Loss : 0.362931191769681
Epoch : 170 Loss : 0.36193234471627717
Epoch : 171 Loss : 0.36093946366506785
Epoch : 172 Loss : 0.3599524955889489
Epoch : 173 Loss : 0.3589713880641523
Epoch : 174 Loss : 0.3579960892622122
Epoch : 175 Loss : 0.3570265479420915
Epoch : 176 Loss : 0.3560627134424201
Epoch : 177 Loss : 0.35510453567382183
Epoch : 178 Loss : 0.3541519651113392
Epoch : 179 Loss : 0.35320495278702374
Epoch : 180 Loss : 0.3522634502825726
Epoch : 181 Loss : 0.3513274097220898
Epoch : 182 Loss : 0.35039678376496625
Epoch : 183 Loss : 0.34947152559884664
Epoch : 184 Loss : 0.34855158893268534
Epoch : 185 Loss : 0.3476369279899356
Epoch : 186 Loss : 0.34672749750181076
Epoch : 187 Loss : 0.3458232527006296
Epoch : 188 Loss : 0.34492414931329674
Epoch : 189 Loss : 0.34403014355483635
Epoch : 190 Loss : 0.3431411921220504
Epoch : 191 Loss : 0.3422572521872553
Epoch : 192 Loss : 0.3413782813920849
Epoch : 193 Loss : 0.3405042378414098
Epoch : 194 Loss : 0.33963508009735854
Epoch : 195 Loss : 0.33877076717337573
Epoch : 196 Loss : 0.3379112585284064
Epoch : 197 Loss : 0.33705651406114506
Epoch : 198 Loss : 0.33620649410436876
Epoch : 199 Loss : 0.33536115941935646
Epoch : 200 Loss : 0.3345204711903904
Epoch : 201 Loss : 0.33368439101930236
Epoch : 202 Loss : 0.33285288092016946
Epoch : 203 Loss : 0.3320259033140116
Epoch : 204 Loss : 0.3312034210235947
Epoch : 205 Loss : 0.3303853972683208
Epoch : 206 Loss : 0.3295717956591628
Epoch : 207 Loss : 0.32876258019371346
Epoch : 208 Loss : 0.3279577152512494
Epoch : 209 Loss : 0.32715716558789154
Epoch : 210 Loss : 0.32636089633186366
Epoch : 211 Loss : 0.32556887297876796
Epoch : 212 Loss : 0.3247810613869607
Epoch : 213 Loss : 0.32399742777299007
Epoch : 214 Loss : 0.323217938707055
Epoch : 215 Loss : 0.3224425611086181
Epoch : 216 Loss : 0.321671262241985
Epoch : 217 Loss : 0.32090400971201033
Epoch : 218 Loss : 0.3201407714598391
Epoch : 219 Loss : 0.31938151575869655
Epoch : 220 Loss : 0.31862621120978074
Epoch : 221 Loss : 0.3178748267381572
Epoch : 222 Loss : 0.3171273315887554
Epoch : 223 Loss : 0.3163836953223954
Epoch : 224 Loss : 0.3156438878118909
Epoch : 225 Loss : 0.31490787923817337
Epoch : 226 Loss : 0.31417564008652893
Epoch : 227 Loss : 0.3134471411427983
Epoch : 228 Loss : 0.3127223534897494
Epoch : 229 Loss : 0.31200124850338357
Epoch : 230 Loss : 0.31128379784935173
Epoch : 231 Loss : 0.3105699734794403
Epoch : 232 Loss : 0.3098597476280525
Epoch : 233 Loss : 0.30915309280876446
Epoch : 234 Loss : 0.30844998181094996
Epoch : 235 Loss : 0.307750387696411
Epoch : 236 Loss : 0.30705428379609195
Epoch : 237 Loss : 0.30636164370681146
Epoch : 238 Loss : 0.30567244128804505
Epoch : 239 Loss : 0.3049866506587772
Epoch : 240 Loss : 0.3043042461943601
Epoch : 241 Loss : 0.30362520252345143
Epoch : 242 Loss : 0.30294949452495556
Epoch : 243 Loss : 0.3022770973250418
Epoch : 244 Loss : 0.30160798629417696
Epoch : 245 Loss : 0.30094213704423317
Epoch : 246 Loss : 0.3002795254255795
Epoch : 247 Loss : 0.2996201275242806
Epoch : 248 Loss : 0.2989639196592711
Epoch : 249 Loss : 0.29831087837961545
Epoch : 250 Loss : 0.2976609804617856
Epoch : 251 Loss : 0.29701420290696756
Epoch : 252 Loss : 0.29637052293841865
Epoch : 253 Loss : 0.2957299179988541
Epoch : 254 Loss : 0.29509236574787734
Epoch : 255 Loss : 0.2944578440594349
Epoch : 256 Loss : 0.29382633101930367
Epoch : 257 Loss : 0.29319780492261777
Epoch : 258 Loss : 0.29257224427144085
Epoch : 259 Loss : 0.291949627772357
Epoch : 260 Loss : 0.29132993433406984
Epoch : 261 Loss : 0.29071314306509555
Epoch : 262 Loss : 0.2900992332714302
Epoch : 263 Loss : 0.28948818445427593
Epoch : 264 Loss : 0.2888799763077795
Epoch : 265 Loss : 0.2882745887168423
Epoch : 266 Loss : 0.28767200175489105
Epoch : 267 Loss : 0.28707219568174075
Epoch : 268 Loss : 0.2864751509414554
Epoch : 269 Loss : 0.28588084816024684
Epoch : 270 Loss : 0.2852892681443868
Epoch : 271 Loss : 0.2847003918781731
Epoch : 272 Loss : 0.2841142005219032
Epoch : 273 Loss : 0.2835306754098652
Epoch : 274 Loss : 0.282949798048393
Epoch : 275 Loss : 0.2823715501139027
Epoch : 276 Loss : 0.2817959134509822
Epoch : 277 Loss : 0.28122287007049623
Epoch : 278 Loss : 0.2806524021477253
Epoch : 279 Loss : 0.2800844920205181
Epoch : 280 Loss : 0.2795191221874621
Epoch : 281 Loss : 0.27895627530611466
Epoch : 282 Loss : 0.27839593419119596
Epoch : 283 Loss : 0.2778380818128707
Epoch : 284 Loss : 0.2772827012949954
Epoch : 285 Loss : 0.27672977591344083
Epoch : 286 Loss : 0.27617928909437633
Epoch : 287 Loss : 0.27563122441265026
Epoch : 288 Loss : 0.2750855655901194
Epoch : 289 Loss : 0.2745422964940303
Epoch : 290 Loss : 0.27400140113544585
Epoch : 291 Loss : 0.27346286366765965
Epoch : 292 Loss : 0.2729266683846145
Epoch : 293 Loss : 0.27239279971940433
Epoch : 294 Loss : 0.27186124224273
Epoch : 295 Loss : 0.2713319806614121
Epoch : 296 Loss : 0.2708049998169101
Epoch : 297 Loss : 0.2702802846838646
Epoch : 298 Loss : 0.2697578203686496
Epoch : 299 Loss : 0.2692375921079568
Epoch : 300 Loss : 0.26871958526738854
Epoch : 301 Loss : 0.26820378534006717
Epoch : 302 Loss : 0.26769017794527006
Epoch : 303 Loss : 0.2671787488270678
Epoch : 304 Loss : 0.2666694838530052
Epoch : 305 Loss : 0.26616236901276147
Epoch : 306 Loss : 0.2656573904168666
Epoch : 307 Loss : 0.2651545342953963
Epoch : 308 Loss : 0.2646537869967313
Epoch : 309 Loss : 0.2641551349862582
Epoch : 310 Loss : 0.26365856484517713
Epoch : 311 Loss : 0.2631640632692561
Epoch : 312 Loss : 0.2626716170676164
Epoch : 313 Loss : 0.26218121316155407
Epoch : 314 Loss : 0.26169283858335113
Epoch : 315 Loss : 0.26120648047512046
Epoch : 316 Loss : 0.26072212608765566
Epoch : 317 Loss : 0.260239762779281
Epoch : 318 Loss : 0.2597593780147481
Epoch : 319 Loss : 0.25928095936412315
Epoch : 320 Loss : 0.25880449450167753
Epoch : 321 Loss : 0.2583299712048368
Epoch : 322 Loss : 0.2578573773530878
Epoch : 323 Loss : 0.25738670092693283
Epoch : 324 Loss : 0.2569179300068484
Epoch : 325 Loss : 0.2564510527722601
Epoch : 326 Loss : 0.25598605750051345
Epoch : 327 Loss : 0.2555229325658768
Epoch : 328 Loss : 0.25506166643856276
Epoch : 329 Loss : 0.25460224768372647
Epoch : 330 Loss : 0.25414466496049126
Epoch : 331 Loss : 0.2536889070210343
Epoch : 332 Loss : 0.25323496270959245
Epoch : 333 Loss : 0.2527828209615592
Epoch : 334 Loss : 0.2523324708025447
Epoch : 335 Loss : 0.2518839013474784
Epoch : 336 Loss : 0.2514371017996856
Epoch : 337 Loss : 0.2509920614500341
Epoch : 338 Loss : 0.25054876967601436
Epoch : 339 Loss : 0.2501072159409013
Epoch : 340 Loss : 0.24966738979286926
Epoch : 341 Loss : 0.2492292808641675
Epoch : 342 Loss : 0.24879287887026968
Epoch : 343 Loss : 0.24835817360904022
Epoch : 344 Loss : 0.24792515495991968
Epoch : 345 Loss : 0.24749381288312738
Epoch : 346 Loss : 0.24706413741884167
Epoch : 347 Loss : 0.24663611868641586
Epoch : 348 Loss : 0.24620974688360991
Epoch : 349 Loss : 0.24578501228579522
Epoch : 350 Loss : 0.2453619052452111
Epoch : 351 Loss : 0.24494041619019424
Epoch : 352 Loss : 0.2445205356244487
Epoch : 353 Loss : 0.2441022541263087
Epoch : 354 Loss : 0.2436855623479859
Epoch : 355 Loss : 0.24327045101487485
Epoch : 356 Loss : 0.24285691092483924
Epoch : 357 Loss : 0.24244493294748135
Epoch : 358 Loss : 0.24203450802349846
Epoch : 359 Loss : 0.24162562716393482
Epoch : 360 Loss : 0.24121828144954882
Epoch : 361 Loss : 0.24081246203011367
Epoch : 362 Loss : 0.24040816012376995
Epoch : 363 Loss : 0.240005367016361
Epoch : 364 Loss : 0.23960407406077808
Epoch : 365 Loss : 0.23920427267632927
Epoch : 366 Loss : 0.2388059543481079
Epoch : 367 Loss : 0.23840911062634856
Epoch : 368 Loss : 0.23801373312582055
Epoch : 369 Loss : 0.23761981352521214
Epoch : 370 Loss : 0.23722734356652078
Epoch : 371 Loss : 0.23683631505445765
Epoch : 372 Loss : 0.2364467198558499
Epoch : 373 Loss : 0.23605854989906017
Epoch : 374 Loss : 0.2356717971734055
Epoch : 375 Loss : 0.23528645372857723
Epoch : 376 Loss : 0.23490251167409051
Epoch : 377 Loss : 0.23451996317870322
Epoch : 378 Loss : 0.23413880046988522
Epoch : 379 Loss : 0.2337590158332353
Epoch : 380 Loss : 0.2333806016119891
Epoch : 381 Loss : 0.23300355020643918
Epoch : 382 Loss : 0.23262785407341632
Epoch : 383 Loss : 0.2322535057257881
Epoch : 384 Loss : 0.2318804977319046
Epoch : 385 Loss : 0.23150882271512027
Epoch : 386 Loss : 0.23113847335325846
Epoch : 387 Loss : 0.23076944237812583
Epoch : 388 Loss : 0.2304017225750141
Epoch : 389 Loss : 0.23003530678220893
Epoch : 390 Loss : 0.2296701878904981
Epoch : 391 Loss : 0.22930635884270048
Epoch : 392 Loss : 0.22894381263319302
Epoch : 393 Loss : 0.22858254230742076
Epoch : 394 Loss : 0.22822254096146402
Epoch : 395 Loss : 0.22786380174155577
Epoch : 396 Loss : 0.22750631784363157
Epoch : 397 Loss : 0.22715008251288324
Epoch : 398 Loss : 0.22679508904331874
Epoch : 399 Loss : 0.22644133077730402
Epoch : 400 Loss : 0.22608880110515595
Epoch : 401 Loss : 0.22573749346467567
Epoch : 402 Loss : 0.22538740134076368
Epoch : 403 Loss : 0.22503851826496038
Epoch : 404 Loss : 0.2246908378150567
Epoch : 405 Loss : 0.22434435361467003
Epoch : 406 Loss : 0.22399905933282782
Epoch : 407 Loss : 0.22365494868358335
Epoch : 408 Loss : 0.22331201542559864
Epoch : 409 Loss : 0.22297025336175452
Epoch : 410 Loss : 0.2226296563387699
Epoch : 411 Loss : 0.22229021824680448
Epoch : 412 Loss : 0.22195193301906532
Epoch : 413 Loss : 0.22161479463144587
Epoch : 414 Loss : 0.2212787971021511
Epoch : 415 Loss : 0.2209439344913149
Epoch : 416 Loss : 0.22061020090063374
Epoch : 417 Loss : 0.22027759047301418
Epoch : 418 Loss : 0.21994609739220605
Epoch : 419 Loss : 0.21961571588244047
Epoch : 420 Loss : 0.2192864402080943
Epoch : 421 Loss : 0.21895826467332413
Epoch : 422 Loss : 0.2186311836217307
Epoch : 423 Loss : 0.2183051914360212
Epoch : 424 Loss : 0.21798028253765353
Epoch : 425 Loss : 0.21765645138653716
Epoch : 426 Loss : 0.21733369248065662
Epoch : 427 Loss : 0.21701200035577584
Epoch : 428 Loss : 0.21669136958510715
Epoch : 429 Loss : 0.21637179477899293
Epoch : 430 Loss : 0.216053270584572
Epoch : 431 Loss : 0.21573579168548385
Epoch : 432 Loss : 0.21541935280155508
Epoch : 433 Loss : 0.21510394868848376
Epoch : 434 Loss : 0.21478957413753555
Epoch : 435 Loss : 0.21447622397524324
Epoch : 436 Loss : 0.21416389306311925
Epoch : 437 Loss : 0.21385257629733806
Epoch : 438 Loss : 0.21354226860846612
Epoch : 439 Loss : 0.2132329649611563
Epoch : 440 Loss : 0.21292466035386703
Epoch : 441 Loss : 0.21261734981857705
Epoch : 442 Loss : 0.21231102842051014
Epoch : 443 Loss : 0.21200569125784857
Epoch : 444 Loss : 0.21170133346145825
Epoch : 445 Loss : 0.2113979501946219
Epoch : 446 Loss : 0.21109553665276712
Epoch : 447 Loss : 0.21079408806319685
Epoch : 448 Loss : 0.21049359968482712
Epoch : 449 Loss : 0.21019406680792205
Epoch : 450 Loss : 0.20989548475383196
Epoch : 451 Loss : 0.2095978488747514
Epoch : 452 Loss : 0.2093011545534431
Epoch : 453 Loss : 0.2090053972030008
Epoch : 454 Loss : 0.2087105722666012
Epoch : 455 Loss : 0.20841667521724808
Epoch : 456 Loss : 0.20812370155752913
Epoch : 457 Loss : 0.20783164681937577
Epoch : 458 Loss : 0.20754050656383585
Epoch : 459 Loss : 0.2072502763808121
Epoch : 460 Loss : 0.20696095188884003
Epoch : 461 Loss : 0.206672528734862
Epoch : 462 Loss : 0.20638500259398865
Epoch : 463 Loss : 0.20609836916926552
Epoch : 464 Loss : 0.20581262419145646
Epoch : 465 Loss : 0.20552776341881696
Epoch : 466 Loss : 0.20524378263686618
Epoch : 467 Loss : 0.2049606776581857
Epoch : 468 Loss : 0.204678444322171
Epoch : 469 Loss : 0.20439707849484587
Epoch : 470 Loss : 0.2041165760686452
Epoch : 471 Loss : 0.20383693296217487
Epoch : 472 Loss : 0.20355814512004322
Epoch : 473 Loss : 0.20328020851261683
Epoch : 474 Loss : 0.20300311913585434
Epoch : 475 Loss : 0.2027268730110662
Epoch : 476 Loss : 0.20245146618472645
Epoch : 477 Loss : 0.20217689472828848
Epoch : 478 Loss : 0.20190315473796716
Epoch : 479 Loss : 0.2016302423345426
Epoch : 480 Loss : 0.20135815366318824
Epoch : 481 Loss : 0.20108688489325813
Epoch : 482 Loss : 0.20081643221810283
Epoch : 483 Loss : 0.20054679185488652
Epoch : 484 Loss : 0.20027796004438603
Epoch : 485 Loss : 0.20000993305082537
Epoch : 486 Loss : 0.1997427071616724
Epoch : 487 Loss : 0.19947627868747925
Epoch : 488 Loss : 0.1992106439616796
Epoch : 489 Loss : 0.1989457993404335
Epoch : 490 Loss : 0.1986817412024252
Epoch : 491 Loss : 0.19841846594871548
Epoch : 492 Loss : 0.19815597000254634
Epoch : 493 Loss : 0.19789424980918327
Epoch : 494 Loss : 0.19763330183573988
Epoch : 495 Loss : 0.19737312257101278
Epoch : 496 Loss : 0.19711370852530694
Epoch : 497 Loss : 0.19685505623027774
Epoch : 498 Loss : 0.19659716223876683
Epoch : 499 Loss : 0.19634002312463594
Epoch : 500 Loss : 0.19608363548261107
Epoch : 501 Loss : 0.19582799592811875
Epoch : 502 Loss : 0.19557310109712764
Epoch : 503 Loss : 0.1953189476460004
Epoch : 504 Loss : 0.19506553225132528
Epoch : 505 Loss : 0.19481285160977999
Epoch : 506 Loss : 0.1945609024379574
Epoch : 507 Loss : 0.19430968147223357
Epoch : 508 Loss : 0.19405918546861703
Epoch : 509 Loss : 0.1938094112025815
Epoch : 510 Loss : 0.19356035546894368
Epoch : 511 Loss : 0.19331201508170887
Epoch : 512 Loss : 0.19306438687391533
Epoch : 513 Loss : 0.19281746769750796
Epoch : 514 Loss : 0.19257125442318782
Epoch : 515 Loss : 0.19232574394027527
Epoch : 516 Loss : 0.1920809331565748
Epoch : 517 Loss : 0.19183681899821792
Epoch : 518 Loss : 0.19159339840956138
Epoch : 519 Loss : 0.19135066835301265
Epoch : 520 Loss : 0.1911086258089261
Epoch : 521 Loss : 0.1908672677754585
Epoch : 522 Loss : 0.1906265912684296
Epoch : 523 Loss : 0.19038659332121075

In [13]:
def label_generator(x):
      z = []
      for prob in x:
        if prob > 0.5:
          z.append(1)
        else:
          z.append(0)
      return z
(labels == label_generator(model.predict(df.to_numpy()))).value_counts()

label
True     45888
False      233
Name: count, dtype: int64

In [15]:
tdf = pd.read_csv('test_binary.csv')

In [16]:
tdf.shape

(25000, 25)

In [17]:
for col in tdf.columns:
  a = metric.loc[metric.label == col]
  tdf[col] = (tdf[col] - np.float128(a.iloc[:,1].to_numpy()))/np.float128(a.iloc[:,2].to_numpy())

In [18]:
pred_labels = label_generator(model.predict(tdf.to_numpy()))

In [19]:
pd.value_counts(pred_labels)

/tmp/ipython-input-3154038371.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(pred_labels)
/tmp/ipython-input-3154038371.py:1: FutureWarning: value_counts with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  pd.value_counts(pred_labels)

1    21955
0     3045
Name: count, dtype: int64

In [20]:
preddf = pd.DataFrame({'prediction' : pred_labels})
preddf.to_csv('val_binary.csv')