In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('train_binary.csv')

In [3]:
df.describe()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,label
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,500.646426,0.499961,5001.475347,99.663713,0.005001,50004.809044,475.641138,0.459966,4401.601767,84.672616,...,74.912848,0.999289,2495.055679,115.182153,0.591371,2056.161274,1.277149,0.003311,-0.002680,0.303600
std,102.167451,0.010176,1018.686318,50.946605,0.001021,10193.068407,97.407907,0.009576,899.975387,44.935452,...,25.024744,0.100383,498.380114,27.473200,0.159825,418.518026,0.666971,1.042740,1.000006,0.459817
min,44.552292,0.462030,966.650179,-130.775155,0.000618,6888.787646,37.323957,0.421474,877.269883,-106.825468,...,-20.047149,0.540305,476.137094,41.911967,0.156876,729.555101,0.008627,-9.263822,-1.000000,0.000000
25%,431.558647,0.493091,4313.706744,65.277365,0.004320,43098.759523,409.719004,0.453495,3794.988088,54.217184,...,57.922540,0.932153,2156.137582,94.564638,0.471014,1686.072685,0.775074,-0.375392,-1.000000,0.000000
50%,500.723423,0.499944,5000.138426,99.838686,0.005002,50049.357109,475.743828,0.459978,4403.108013,84.700557,...,74.865170,0.999356,2497.297022,108.480117,0.546799,2181.189715,1.203037,0.000198,-1.000000,0.000000
75%,570.043673,0.506870,5686.792287,134.056839,0.005688,56864.960088,541.822674,0.466470,5008.693250,115.092937,...,91.921637,1.066220,2832.091910,136.839835,0.728151,2371.657805,1.692574,0.380763,1.000000,1.000000
max,930.857578,0.541910,9061.589352,332.284250,0.008894,95723.410815,882.181943,0.498576,8043.777043,272.166998,...,174.186524,1.461638,4572.047464,208.654969,1.167666,3058.142671,4.946865,9.609629,1.000000,1.000000

In [4]:
testdf = df.sample(frac = 0.1,random_state=42)
df.drop(testdf.index,inplace = True)

In [5]:
labels = df.label

In [6]:
df = df.drop('label',axis = 1)

In [7]:
metric = pd.DataFrame({'label' : df.columns,
              'mean' : np.mean(df,axis =0),
              'std' : np.std(df,axis = 0)})

In [8]:
metric

                 label          mean           std
feature_0    feature_0    500.704484    102.302295
feature_1    feature_1      0.499940      0.010177
feature_2    feature_2   5001.771907   1019.728403
feature_3    feature_3     99.629040     50.893473
feature_4    feature_4      0.005000      0.001023
feature_5    feature_5  50020.644856  10183.702577
feature_6    feature_6    475.699537     97.535083
feature_7    feature_7      0.459947      0.009577
feature_8    feature_8   4401.869549    900.925917
feature_9    feature_9     84.622903     44.877985
feature_10  feature_10      1.046626      1.469247
feature_11  feature_11     -0.000491      1.038233
feature_12  feature_12      0.001285      0.705486
feature_13  feature_13      1.955462      0.767869
feature_14  feature_14     -0.002687      0.422211
feature_15  feature_15      8.404665      3.478023
feature_16  feature_16     74.887839     25.020290
feature_17  feature_17      0.999299      0.100586
feature_18  feature_18   2494.293003    498.525340
feature_19  feature_19    115.227654     27.469672
feature_20  feature_20      0.591396      0.160021
feature_21  feature_21   2055.576653    418.278362
feature_22  feature_22      1.277327      0.666632
feature_23  feature_23      0.005343      1.046086
feature_24  feature_24     -0.003067      0.999995

In [9]:
for col in df.columns:
    if col == 'label':
        continue
    df[col] = (df[col] - np.mean(df[col]))/np.std(df[col])

In [10]:
class LogisticRegression:
    def __init__(self):
        self.optimizer = None
        self.hat_m_b = None
        self.hat_m_w = None
        self.r_v_b = None
        self.r_v_w = None
        self.hat_v_w = None
        self.hat_v_b = None
        self.x = None
        self.y = None
        self._y = None
        self.w = None
        self.b = None
        self.w_error = None
        self.b_error = None
        self.m_w = None
        self.m_b = None
        self.v_w = None
        self.v_b = None
        self.epoch_count = 1
        self.epoch_limit = None
    def predict(self,x):
        out = 1/(1 + np.exp(-(np.dot(x , self.w) + self.b)))
        return out
    def fit(self,x,y,epochs = 100,optimizer = 'gd'):
        self.x = x
        self.y = y
        self.w = np.zeros(x.shape[1])
        self.b = 0
        self._y = self.predict(self.x)
        self.epoch_limit = epochs
        self.optimizer = optimizer
        #initialized the momentum to avoid type error in first iteration
        self.v_w = np.zeros(self.x.shape[1])
        self.m_w = np.zeros(self.x.shape[1])
        self.m_b = 0
        self.v_b = 0
        #####
        self.b_error = -(np.mean(self.y - self._y))
        self.w_error = -(np.dot(self.x.transpose(),self.y - self._y))/self.x.shape[0]
        if self.optimizer == "adam":
            update_step = self.adam
        elif self.optimizer == "RMSprop":
            update_step = self.RMSprop
        elif self.optimizer == "momentum":
            update_step = self.momentum
        elif self.optimizer == "gd":
            update_step = self.gd
        else:
            raise ValueError(f"Unknown optimizer: {self.optimizer}")
        while self.epoch_count <= self.epoch_limit:
            self._y = self.predict(self.x)
            self.loss = sum([-t_hat*np.log(t) - (1-t_hat)*np.log(1-t) for t , t_hat in zip(self._y,self.y)])/len(self.y)
            self.b_error = -(np.mean(self.y - self._y))
            self.w_error = -(np.dot(self.x.transpose(),self.y - self._y))/self.x.shape[0]
            update_step()
            print(f'Epoch : {self.epoch_count} Loss : {self.loss}')
            self.epoch_count += 1
    def adam(self, beta1 = 0.9 , beta2 = 0.999 ,epsilon = 10**-8,gamma = 0.0003):
        #momentum variables
        self.m_w = beta1*self.m_w + (1 - beta1)*self.w_error
        self.m_b = beta1*self.m_b + (1 - beta1)*self.b_error
        #RMSpropFactors
        self.v_w = beta2*self.v_w + (1-beta2)*(self.w_error**2)
        self.v_b = beta2*self.v_b + (1-beta2)*(self.b_error**2)
        #bias correcting the variance values
        self.hat_v_w = self.v_w / (1 - beta2**self.epoch_count)
        self.hat_v_b = self.v_b / (1 - beta2**self.epoch_count)
        #RMSpropFactvectors for updating the final values
        self.r_v_w = 1 / (np.sqrt(self.hat_v_w + epsilon))
        self.r_v_b = 1 / (np.sqrt(self.hat_v_b + epsilon))
        #bias correcting the momentum values
        self.hat_m_w = self.m_w / (1 - beta1**self.epoch_count)
        self.hat_m_b = self.m_b / (1 - beta1**self.epoch_count)
        #Updating the final value
        self.b = self.b - self.hat_m_b*self.r_v_b*gamma
        self.w = self.w - np.multiply(self.hat_m_w,self.r_v_w)*gamma
    def RMSprop(self,beta2 = 0.999,epsilon = 10**-8, gamma = 0.001):
        self.v_w = beta2*self.v_w + (1-beta2)*(self.w_error**2)
        self.v_b = beta2*self.v_b + (1-beta2)*(self.b_error**2)
        self.r_v_w = 1 / (np.sqrt(self.v_w + epsilon))
        self.r_v_b = 1 / (np.sqrt(self.v_b + epsilon))
        self.b = self.b - self.b_error*self.r_v_b*gamma
        self.w = self.w - np.multiply(self.w_error,self.r_v_w)*gamma
    def momentum(self,beta1 = 0.9 , gamma = 0.001):
        self.m_w = beta1*self.m_w + (1 - beta1)*self.w_error
        self.m_b = beta1*self.m_b + (1 - beta1)*self.b_error
        self.b = self.b - self.m_b*gamma
        self.w = self.w - self.m_w*gamma
    def gd(self,gamma = 0.005):
        self.w = self.w - gamma*self.w_error
        self.b = self.b - self.b_error*gamma

In [12]:
model = LogisticRegression()
model.fit(df.to_numpy(),labels,optimizer='gd',epochs=1000)

Epoch : 1 Loss : 0.6931471805592402
Epoch : 2 Loss : 0.6894101154210465
Epoch : 3 Loss : 0.6857085753035498
Epoch : 4 Loss : 0.6820422014040913
Epoch : 5 Loss : 0.6784106364095968
Epoch : 6 Loss : 0.6748135245874306
Epoch : 7 Loss : 0.6712505118719375
Epoch : 8 Loss : 0.667721245947342
Epoch : 9 Loss : 0.6642253763270235
Epoch : 10 Loss : 0.6607625544292728
Epoch : 11 Loss : 0.6573324336494574
Epoch : 12 Loss : 0.6539346694289263
Epoch : 13 Loss : 0.6505689193203223
Epoch : 14 Loss : 0.6472348430496473
Epoch : 15 Loss : 0.6439321025750753
Epoch : 16 Loss : 0.6406603621424901
Epoch : 17 Loss : 0.6374192883379249
Epoch : 18 Loss : 0.6342085501368898
Epoch : 19 Loss : 0.6310278189506918
Epoch : 20 Loss : 0.6278767686698581
Epoch : 21 Loss : 0.6247550757045286
Epoch : 22 Loss : 0.6216624190223119
Epoch : 23 Loss : 0.6185984801831668
Epoch : 24 Loss : 0.6155629433717253
Epoch : 25 Loss : 0.612555495427017
Epoch : 26 Loss : 0.6095758258697602
Epoch : 27 Loss : 0.6066236269270618
Epoch : 28 Loss : 0.6036985935548783
Epoch : 29 Loss : 0.6008004234581571
Epoch : 30 Loss : 0.5979288171087209
Epoch : 31 Loss : 0.5950834777610663
Epoch : 32 Loss : 0.5922641114660243
Epoch : 33 Loss : 0.5894704270825104
Epoch : 34 Loss : 0.5867021362872251
Epoch : 35 Loss : 0.5839589535826102
Epoch : 36 Loss : 0.58124059630292
Epoch : 37 Loss : 0.5785467846186304
Epoch : 38 Loss : 0.5758772415391746
Epoch : 39 Loss : 0.5732316929140374
Epoch : 40 Loss : 0.5706098674324245
Epoch : 41 Loss : 0.5680114966213441
Epoch : 42 Loss : 0.5654363148424186
Epoch : 43 Loss : 0.562884059287224
Epoch : 44 Loss : 0.5603544699714316
Epoch : 45 Loss : 0.5578472897277277
Epoch : 46 Loss : 0.5553622641975029
Epoch : 47 Loss : 0.5528991418214766
Epoch : 48 Loss : 0.5504576738292977
Epoch : 49 Loss : 0.5480376142280207
Epoch : 50 Loss : 0.5456387197897997
Epoch : 51 Loss : 0.5432607500384883
Epoch : 52 Loss : 0.5409034672355579
Epoch : 53 Loss : 0.5385666363650459
Epoch : 54 Loss : 0.5362500251179034
Epoch : 55 Loss : 0.5339534038754908
Epoch : 56 Loss : 0.5316765456924438
Epoch : 57 Loss : 0.5294192262789417
Epoch : 58 Loss : 0.5271812239822982
Epoch : 59 Loss : 0.5249623197680652
Epoch : 60 Loss : 0.5227622972006254
Epoch : 61 Loss : 0.5205809424231838
Epoch : 62 Loss : 0.518418044137461
Epoch : 63 Loss : 0.5162733935828978
Epoch : 64 Loss : 0.5141467845154722
Epoch : 65 Loss : 0.5120380131861544
Epoch : 66 Loss : 0.5099468783191047
Epoch : 67 Loss : 0.5078731810894845
Epoch : 68 Loss : 0.5058167251010789
Epoch : 69 Loss : 0.5037773163636671
Epoch : 70 Loss : 0.5017547632701123
Epoch : 71 Loss : 0.4997488765733425
Epoch : 72 Loss : 0.49775946936313725
Epoch : 73 Loss : 0.49578635704276997
Epoch : 74 Loss : 0.49382935730548005
Epoch : 75 Loss : 0.49188829011094665
Epoch : 76 Loss : 0.48996297766157826
Epoch : 77 Loss : 0.48805324437879827
Epoch : 78 Loss : 0.4861589168792603
Epoch : 79 Loss : 0.4842798239510222
Epoch : 80 Loss : 0.4824157965297428
Epoch : 81 Loss : 0.48056666767485684
Epoch : 82 Loss : 0.47873227254575684
Epoch : 83 Loss : 0.4769124483780356
Epoch : 84 Loss : 0.4751070344597258
Epoch : 85 Loss : 0.4733158721076586
Epoch : 86 Loss : 0.47153880464381276
Epoch : 87 Loss : 0.469775677371825
Epoch : 88 Loss : 0.4680263375535188
Epoch : 89 Loss : 0.46629063438557494
Epoch : 90 Loss : 0.4645684189762751
Epoch : 91 Loss : 0.4628595443224234
Epoch : 92 Loss : 0.4611638652863043
Epoch : 93 Loss : 0.4594812385728741
Epoch : 94 Loss : 0.45781152270699876
Epoch : 95 Loss : 0.45615457801089715
Epoch : 96 Loss : 0.45451026658172533
Epoch : 97 Loss : 0.4528784522693241
Epoch : 98 Loss : 0.45125900065410823
Epoch : 99 Loss : 0.4496517790251464
Epoch : 100 Loss : 0.4480566563584089
Epoch : 101 Loss : 0.4464735032952245
Epoch : 102 Loss : 0.44490219212083804
Epoch : 103 Loss : 0.4433425967432797
Epoch : 104 Loss : 0.4417945926722744
Epoch : 105 Loss : 0.44025805699850995
Epoch : 106 Loss : 0.438732868372914
Epoch : 107 Loss : 0.4372189069863617
Epoch : 108 Loss : 0.4357160545493263
Epoch : 109 Loss : 0.43422419427191766
Epoch : 110 Loss : 0.4327432108440928
Epoch : 111 Loss : 0.4312729904159984
Epoch : 112 Loss : 0.4298134205785588
Epoch : 113 Loss : 0.428364390344363
Epoch : 114 Loss : 0.42692579012857546
Epoch : 115 Loss : 0.42549751173022893
Epoch : 116 Loss : 0.4240794483136402
Epoch : 117 Loss : 0.4226714943900453
Epoch : 118 Loss : 0.4212735457994615
Epoch : 119 Loss : 0.41988549969277567
Epoch : 120 Loss : 0.41850725451397464
Epoch : 121 Loss : 0.4171387099826729
Epoch : 122 Loss : 0.41577976707679004
Epoch : 123 Loss : 0.4144303280154545
Epoch : 124 Loss : 0.41309029624214477
Epoch : 125 Loss : 0.41175957640797084
Epoch : 126 Loss : 0.41043807435525614
Epoch : 127 Loss : 0.4091256971012245
Epoch : 128 Loss : 0.4078223528219629
Epoch : 129 Loss : 0.4065279508365927
Epoch : 130 Loss : 0.4052424015915589
Epoch : 131 Loss : 0.4039656166452598
Epoch : 132 Loss : 0.40269750865272236
Epoch : 133 Loss : 0.4014379913505994
Epoch : 134 Loss : 0.4001869795423065
Epoch : 135 Loss : 0.3989443890833752
Epoch : 136 Loss : 0.39771013686696227
Epoch : 137 Loss : 0.39648414080961536
Epoch : 138 Loss : 0.39526631983718213
Epoch : 139 Loss : 0.3940565938709216
Epoch : 140 Loss : 0.39285488381381034
Epoch : 141 Loss : 0.3916611115370321
Epoch : 142 Loss : 0.390475199866632
Epoch : 143 Loss : 0.3892970725703944
Epoch : 144 Loss : 0.38812665434487226
Epoch : 145 Loss : 0.38696387080258565
Epoch : 146 Loss : 0.3858086484594445
Epoch : 147 Loss : 0.38466091472228053
Epoch : 148 Loss : 0.3835205978766098
Epoch : 149 Loss : 0.38238762707454854
Epoch : 150 Loss : 0.3812619323228701
Epoch : 151 Loss : 0.38014344447128273
Epoch : 152 Loss : 0.3790320952008189
Epoch : 153 Loss : 0.3779278170124377
Epoch : 154 Loss : 0.37683054321576065
Epoch : 155 Loss : 0.37574020791794327
Epoch : 156 Loss : 0.374656746012783
Epoch : 157 Loss : 0.3735800931698937
Epoch : 158 Loss : 0.372510185824094
Epoch : 159 Loss : 0.3714469611649239
Epoch : 160 Loss : 0.37039035712631624
Epoch : 161 Loss : 0.36934031237642123
Epoch : 162 Loss : 0.3682967663075638
Epoch : 163 Loss : 0.3672596590263608
Epoch : 164 Loss : 0.3662289313439742
Epoch : 165 Loss : 0.3652045247665097
Epoch : 166 Loss : 0.36418638148554455
Epoch : 167 Loss : 0.36317444436880897
Epoch : 168 Loss : 0.3621686569509661
Epoch : 169 Loss : 0.36116896342458626
Epoch : 170 Loss : 0.3601753086311854
Epoch : 171 Loss : 0.35918763805247106
Epoch : 172 Loss : 0.3582058978016101
Epoch : 173 Loss : 0.3572300346147483
Epoch : 174 Loss : 0.35625999584252954
Epoch : 175 Loss : 0.3552957294418561
Epoch : 176 Loss : 0.3543371839676653
Epoch : 177 Loss : 0.353384308564908
Epoch : 178 Loss : 0.3524370529605842
Epoch : 179 Loss : 0.3514953674559327
Epoch : 180 Loss : 0.35055920291871956
Epoch : 181 Loss : 0.3496285107756415
Epoch : 182 Loss : 0.34870324300484556
Epoch : 183 Loss : 0.34778335212854466
Epoch : 184 Loss : 0.3468687912057629
Epoch : 185 Loss : 0.3459595138251461
Epoch : 186 Loss : 0.3450554740979456
Epoch : 187 Loss : 0.3441566266510402
Epoch : 188 Loss : 0.3432629266200798
Epoch : 189 Loss : 0.34237432964275116
Epoch : 190 Loss : 0.34149079185210884
Epoch : 191 Loss : 0.34061226987003185
Epoch : 192 Loss : 0.3397387208007662
Epoch : 193 Loss : 0.33887010222452785
Epoch : 194 Loss : 0.3380063721912813
Epoch : 195 Loss : 0.33714748921452103
Epoch : 196 Loss : 0.3362934122651903
Epoch : 197 Loss : 0.33544410076568754
Epoch : 198 Loss : 0.3345995145839303
Epoch : 199 Loss : 0.33375961402756354
Epoch : 200 Loss : 0.332924359838184
Epoch : 201 Loss : 0.3320937131856923
Epoch : 202 Loss : 0.3312676356627165
Epoch : 203 Loss : 0.33044608927911817
Epoch : 204 Loss : 0.3296290364565692
Epoch : 205 Loss : 0.3288164400232262
Epoch : 206 Loss : 0.3280082632084532
Epoch : 207 Loss : 0.32720446963765987
Epoch : 208 Loss : 0.32640502332716625
Epoch : 209 Loss : 0.3256098886791989
Epoch : 210 Loss : 0.3248190304769055
Epoch : 211 Loss : 0.3240324138794735
Epoch : 212 Loss : 0.32325000441731255
Epoch : 213 Loss : 0.32247176798730803
Epoch : 214 Loss : 0.32169767084812045
Epoch : 215 Loss : 0.3209276796156107
Epoch : 216 Loss : 0.3201617612582422
Epoch : 217 Loss : 0.31939988309264694
Epoch : 218 Loss : 0.3186420127791783
Epoch : 219 Loss : 0.3178881183175642
Epoch : 220 Loss : 0.31713816804262535
Epoch : 221 Loss : 0.31639213062003263
Epoch : 222 Loss : 0.31564997504214676
Epoch : 223 Loss : 0.3149116706239071
Epoch : 224 Loss : 0.3141771869987613
Epoch : 225 Loss : 0.31344649411471487
Epoch : 226 Loss : 0.31271956223035213
Epoch : 227 Loss : 0.3119963619109898
Epoch : 228 Loss : 0.3112768640248111
Epoch : 229 Loss : 0.31056103973914695
Epoch : 230 Loss : 0.3098488605167153
Epoch : 231 Loss : 0.3091402981119788
Epoch : 232 Loss : 0.30843532456752965
Epoch : 233 Loss : 0.30773391221051877
Epoch : 234 Loss : 0.30703603364915927
Epoch : 235 Loss : 0.30634166176925726
Epoch : 236 Loss : 0.3056507697307896
Epoch : 237 Loss : 0.3049633309645624
Epoch : 238 Loss : 0.3042793191688694
Epoch : 239 Loss : 0.30359870830623337
Epoch : 240 Loss : 0.3029214726001793
Epoch : 241 Loss : 0.3022475865320679
Epoch : 242 Loss : 0.30157702483792864
Epoch : 243 Loss : 0.3009097625053899
Epoch : 244 Loss : 0.3002457747706401
Epoch : 245 Loss : 0.2995850371153907
Epoch : 246 Loss : 0.2989275252639493
Epoch : 247 Loss : 0.29827321518025945
Epoch : 248 Loss : 0.2976220830650465
Epoch : 249 Loss : 0.29697410535295704
Epoch : 250 Loss : 0.2963292587097789
Epoch : 251 Loss : 0.2956875200296434
Epoch : 252 Loss : 0.295048866432322
Epoch : 253 Loss : 0.2944132752605364
Epoch : 254 Loss : 0.29378072407730105
Epoch : 255 Loss : 0.29315119066330525
Epoch : 256 Loss : 0.29252465301434116
Epoch : 257 Loss : 0.29190108933875536
Epoch : 258 Loss : 0.2912804780549338
Epoch : 259 Loss : 0.29066279778884524
Epoch : 260 Loss : 0.29004802737158036
Epoch : 261 Loss : 0.28943614583694327
Epoch : 262 Loss : 0.28882713241909763
Epoch : 263 Loss : 0.28822096655020624
Epoch : 264 Loss : 0.2876176278581101
Epoch : 265 Loss : 0.2870170961640783
Epoch : 266 Loss : 0.28641935148053055
Epoch : 267 Loss : 0.2858243740088327
Epoch : 268 Loss : 0.2852321441371
Epoch : 269 Loss : 0.2846426424380519
Epoch : 270 Loss : 0.28405584966685876
Epoch : 271 Loss : 0.2834717467590648
Epoch : 272 Loss : 0.28289031482849514
Epoch : 273 Loss : 0.28231153516520585
Epoch : 274 Loss : 0.28173538923349645
Epoch : 275 Loss : 0.2811618586698813
Epoch : 276 Loss : 0.2805909252811465
Epoch : 277 Loss : 0.2800225710424065
Epoch : 278 Loss : 0.279456778095176
Epoch : 279 Loss : 0.2788935287455097
Epoch : 280 Loss : 0.27833280546211603
Epoch : 281 Loss : 0.27777459087452167
Epoch : 282 Loss : 0.27721886777126814
Epoch : 283 Loss : 0.27666561909810555
Epoch : 284 Loss : 0.276114827956247
Epoch : 285 Loss : 0.2755664776005961
Epoch : 286 Loss : 0.27502055143805987
Epoch : 287 Loss : 0.27447703302581816
Epoch : 288 Loss : 0.2739359060696682
Epoch : 289 Loss : 0.2733971544223616
Epoch : 290 Loss : 0.2728607620819705
Epoch : 291 Loss : 0.2723267131902898
Epoch : 292 Loss : 0.27179499203122415
Epoch : 293 Loss : 0.2712655830292262
Epoch : 294 Loss : 0.2707384707477614
Epoch : 295 Loss : 0.270213639887763
Epoch : 296 Loss : 0.26969107528611536
Epoch : 297 Loss : 0.26917076191418066
Epoch : 298 Loss : 0.2686526848763263
Epoch : 299 Loss : 0.26813682940844724
Epoch : 300 Loss : 0.2676231808765639
Epoch : 301 Loss : 0.26711172477539363
Epoch : 302 Loss : 0.2666024467269404
Epoch : 303 Loss : 0.2660953324791385
Epoch : 304 Loss : 0.2655903679044678
Epoch : 305 Loss : 0.26508753899862647
Epoch : 306 Loss : 0.2645868318791901
Epoch : 307 Loss : 0.26408823278431237
Epoch : 308 Loss : 0.26359172807141856
Epoch : 309 Loss : 0.2630973042159283
Epoch : 310 Loss : 0.262604947810006
Epoch : 311 Loss : 0.26211464556130637
Epoch : 312 Loss : 0.26162638429173757
Epoch : 313 Loss : 0.26114015093625104
Epoch : 314 Loss : 0.2606559325416427
Epoch : 315 Loss : 0.26017371626537866
Epoch : 316 Loss : 0.2596934893743911
Epoch : 317 Loss : 0.2592152392439669
Epoch : 318 Loss : 0.25873895335656943
Epoch : 319 Loss : 0.2582646193007371
Epoch : 320 Loss : 0.25779222476994673
Epoch : 321 Loss : 0.25732175756153786
Epoch : 322 Loss : 0.25685320557560626
Epoch : 323 Loss : 0.2563865568139452
Epoch : 324 Loss : 0.25592179937897763
Epoch : 325 Loss : 0.25545892147271826
Epoch : 326 Loss : 0.2549979113957313
Epoch : 327 Loss : 0.25453875754611055
Epoch : 328 Loss : 0.25408144841848235
Epoch : 329 Loss : 0.2536259726029934
Epoch : 330 Loss : 0.2531723187843327
Epoch : 331 Loss : 0.2527204757407705
Epoch : 332 Loss : 0.2522704323431762
Epoch : 333 Loss : 0.25182217755409075
Epoch : 334 Loss : 0.2513757004267788
Epoch : 335 Loss : 0.25093099010429754
Epoch : 336 Loss : 0.2504880358186056
Epoch : 337 Loss : 0.250046826889627
Epoch : 338 Loss : 0.24960735272437798
Epoch : 339 Loss : 0.2491696028160857
Epoch : 340 Loss : 0.24873356674331007
Epoch : 341 Loss : 0.24829923416908095
Epoch : 342 Loss : 0.24786659484005988
Epoch : 343 Loss : 0.2474356385856795
Epoch : 344 Loss : 0.24700635531733836
Epoch : 345 Loss : 0.2465787350275442
Epoch : 346 Loss : 0.24615276778914963
Epoch : 347 Loss : 0.24572844375450165
Epoch : 348 Loss : 0.2453057531546861
Epoch : 349 Loss : 0.24488468629873103
Epoch : 350 Loss : 0.2444652335728324
Epoch : 351 Loss : 0.24404738543958823
Epoch : 352 Loss : 0.24363113243724968
Epoch : 353 Loss : 0.24321646517896872
Epoch : 354 Loss : 0.2428033743520687
Epoch : 355 Loss : 0.24239185071729472
Epoch : 356 Loss : 0.24198188510811564
Epoch : 357 Loss : 0.2415734684300127
Epoch : 358 Loss : 0.24116659165973778
Epoch : 359 Loss : 0.24076124584468142
Epoch : 360 Loss : 0.2403574221021193
Epoch : 361 Loss : 0.23995511161856317
Epoch : 362 Loss : 0.23955430564911326
Epoch : 363 Loss : 0.23915499551673683
Epoch : 364 Loss : 0.23875717261166138
Epoch : 365 Loss : 0.23836082839070302
Epoch : 366 Loss : 0.23796595437661788
Epoch : 367 Loss : 0.23757254215749082
Epoch : 368 Loss : 0.23718058338609052
Epoch : 369 Loss : 0.23679006977924572
Epoch : 370 Loss : 0.236400993117256
Epoch : 371 Loss : 0.2360133452432589
Epoch : 372 Loss : 0.23562711806264455
Epoch : 373 Loss : 0.23524230354246473
Epoch : 374 Loss : 0.23485889371084373
Epoch : 375 Loss : 0.23447688065638972
Epoch : 376 Loss : 0.2340962565276366
Epoch : 377 Loss : 0.23371701353248206
Epoch : 378 Loss : 0.23333914393760052
Epoch : 379 Loss : 0.23296264006792267
Epoch : 380 Loss : 0.23258749430606884
Epoch : 381 Loss : 0.23221369909180567
Epoch : 382 Loss : 0.23184124692152747
Epoch : 383 Loss : 0.23147013034771063
Epoch : 384 Loss : 0.23110034197839224
Epoch : 385 Loss : 0.23073187447667154
Epoch : 386 Loss : 0.23036472056016516
Epoch : 387 Loss : 0.22999887300053806
Epoch : 388 Loss : 0.22963432462296907
Epoch : 389 Loss : 0.2292710683056788
Epoch : 390 Loss : 0.22890909697943465
Epoch : 391 Loss : 0.22854840362705275
Epoch : 392 Loss : 0.22818898128294646
Epoch : 393 Loss : 0.22783082303262184
Epoch : 394 Loss : 0.22747392201224065
Epoch : 395 Loss : 0.2271182714081243
Epoch : 396 Loss : 0.22676386445632124
Epoch : 397 Loss : 0.22641069444214934
Epoch : 398 Loss : 0.22605875469973233
Epoch : 399 Loss : 0.225708038611568
Epoch : 400 Loss : 0.22535853960809363
Epoch : 401 Loss : 0.2250102511672409
Epoch : 402 Loss : 0.22466316681401652
Epoch : 403 Loss : 0.2243172801200785
Epoch : 404 Loss : 0.22397258470328665
Epoch : 405 Loss : 0.22362907422734582
Epoch : 406 Loss : 0.22328674240133184
Epoch : 407 Loss : 0.22294558297932127
Epoch : 408 Loss : 0.2226055897599882
Epoch : 409 Loss : 0.22226675658619371
Epoch : 410 Loss : 0.22192907734459222
Epoch : 411 Loss : 0.2215925459652511
Epoch : 412 Loss : 0.22125715642125812
Epoch : 413 Loss : 0.22092290272834114
Epoch : 414 Loss : 0.22058977894450554
Epoch : 415 Loss : 0.22025777916961908
Epoch : 416 Loss : 0.21992689754510297
Epoch : 417 Loss : 0.21959712825350447
Epoch : 418 Loss : 0.2192684655181866
Epoch : 419 Loss : 0.21894090360293225
Epoch : 420 Loss : 0.21861443681161088
Epoch : 421 Loss : 0.21828905948783192
Epoch : 422 Loss : 0.21796476601456866
Epoch : 423 Loss : 0.21764155081385236
Epoch : 424 Loss : 0.217319408346408
Epoch : 425 Loss : 0.2169983331113243
Epoch : 426 Loss : 0.21667831964572576
Epoch : 427 Loss : 0.21635936252443785
Epoch : 428 Loss : 0.2160414563596604
Epoch : 429 Loss : 0.21572459580064363
Epoch : 430 Loss : 0.2154087755333917
Epoch : 431 Loss : 0.2150939902803035
Epoch : 432 Loss : 0.2147802347999035
Epoch : 433 Loss : 0.21446750388650387
Epoch : 434 Loss : 0.2141557923699081
Epoch : 435 Loss : 0.21384509511511574
Epoch : 436 Loss : 0.21353540702200283
Epoch : 437 Loss : 0.21322672302504506
Epoch : 438 Loss : 0.21291903809301124
Epoch : 439 Loss : 0.21261234722868147
Epoch : 440 Loss : 0.21230664546853922
Epoch : 441 Loss : 0.21200192788252264
Epoch : 442 Loss : 0.2116981895737019
Epoch : 443 Loss : 0.21139542567802957
Epoch : 444 Loss : 0.21109363136404755
Epoch : 445 Loss : 0.21079280183262125
Epoch : 446 Loss : 0.21049293231666877
Epoch : 447 Loss : 0.2101940180808817
Epoch : 448 Loss : 0.20989605442147619
Epoch : 449 Loss : 0.20959903666591329
Epoch : 450 Loss : 0.20930296017265904
Epoch : 451 Loss : 0.20900782033090748
Epoch : 452 Loss : 0.20871361256032595
Epoch : 453 Loss : 0.20842033231081736
Epoch : 454 Loss : 0.20812797506226194
Epoch : 455 Loss : 0.20783653632427226
Epoch : 456 Loss : 0.2075460116359292
Epoch : 457 Loss : 0.20725639656557387
Epoch : 458 Loss : 0.2069676867105418
Epoch : 459 Loss : 0.20667987769692162
Epoch : 460 Loss : 0.20639296517934805
Epoch : 461 Loss : 0.20610694484073477
Epoch : 462 Loss : 0.205821812392067
Epoch : 463 Loss : 0.20553756357215558
Epoch : 464 Loss : 0.2052541941474276
Epoch : 465 Loss : 0.20497169991168726
Epoch : 466 Loss : 0.2046900766859019
Epoch : 467 Loss : 0.20440932031797704
Epoch : 468 Loss : 0.20412942668254488
Epoch : 469 Loss : 0.20385039168074773
Epoch : 470 Loss : 0.20357221124000388
Epoch : 471 Loss : 0.20329488131383974
Epoch : 472 Loss : 0.20301839788162745
Epoch : 473 Loss : 0.202742756948421
Epoch : 474 Loss : 0.2024679545447282
Epoch : 475 Loss : 0.20219398672630937
Epoch : 476 Loss : 0.2019208495739826
Epoch : 477 Loss : 0.20164853919341166
Epoch : 478 Loss : 0.20137705171493359
Epoch : 479 Loss : 0.20110638329332312
Epoch : 480 Loss : 0.20083653010763217
Epoch : 481 Loss : 0.20056748836099225
Epoch : 482 Loss : 0.20029925428040765
Epoch : 483 Loss : 0.20003182411657863
Epoch : 484 Loss : 0.19976519414371902
Epoch : 485 Loss : 0.19949936065936025
Epoch : 486 Loss : 0.19923431998417163
Epoch : 487 Loss : 0.1989700684617871
Epoch : 488 Loss : 0.19870660245861177
Epoch : 489 Loss : 0.19844391836365197
Epoch : 490 Loss : 0.1981820125883421
Epoch : 491 Loss : 0.19792088156635962
Epoch : 492 Loss : 0.19766052175345405
Epoch : 493 Loss : 0.19740092962728692
Epoch : 494 Loss : 0.19714210168724602
Epoch : 495 Loss : 0.19688403445429017
Epoch : 496 Loss : 0.19662672447076987
Epoch : 497 Loss : 0.1963701683002728
Epoch : 498 Loss : 0.19611436252745063
Epoch : 499 Loss : 0.19585930375787053
Epoch : 500 Loss : 0.19560498861783843
Epoch : 501 Loss : 0.19535141375424714
Epoch : 502 Loss : 0.19509857583442503
Epoch : 503 Loss : 0.19484647154596024
Epoch : 504 Loss : 0.19459509759657012
Epoch : 505 Loss : 0.19434445071393028
Epoch : 506 Loss : 0.19409452764552984
Epoch : 507 Loss : 0.193845325158523
Epoch : 508 Loss : 0.19359684003956834
Epoch : 509 Loss : 0.19334906909468824
Epoch : 510 Loss : 0.19310200914913156
Epoch : 511 Loss : 0.19285565704721
Epoch : 512 Loss : 0.19261000965216601
Epoch : 513 Loss : 0.19236506384602653
Epoch : 514 Loss : 0.1921208165294678
Epoch : 515 Loss : 0.19187726462165813
Epoch : 516 Loss : 0.19163440506014448
Epoch : 517 Loss : 0.1913922348006892
Epoch : 518 Loss : 0.19115075081715363
Epoch : 519 Loss : 0.1909099501013509
Epoch : 520 Loss : 0.1906698296629125
Epoch : 521 Loss : 0.19043038652916816
Epoch : 522 Loss : 0.19019161774500098
Epoch : 523 Loss : 0.18995352037271873

In [13]:

tlabels = testdf.label

In [14]:
testdf.drop('label' , axis = 1, inplace = True)

In [17]:
def label_generator(x):
      z = []
      for prob in x:
        if prob > 0.5:
          z.append(1)
        else:
          z.append(0)
      return z
plabels = label_generator(model.predict(testdf.to_numpy()))

In [18]:
plabels

[1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 ...]

In [26]:
np.array(plabels) == 1

array([ True, False, False, ..., False,  True,  True], shape=(5000,))

In [27]:
def f1_score(y_true, y_pred, threshold=0.5):
    
    y_true = np.array(y_true)
    
    
    tp = np.sum((y_true == 1) & (y_pred == 1))
    fp = np.sum((y_true == 0) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))
    
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
    
    return f1
f1_score(np.array(tlabels),np.array(plabels))

np.float64(0.9929883138564274)

In [28]:
tdf = pd.read_csv('test_binary.csv')

In [29]:
tdf.shape

(25000, 25)

In [30]:
for col in tdf.columns:
      a = metric.loc[metric.label == col]
      std = np.float64(a.iloc[:,2].to_numpy())
      mean = np.float64(a.iloc[:,1].to_numpy())
      tdf[col] = (tdf[col] - mean)/std

C:\Users\ashis\AppData\Local\Temp\ipykernel_14140\46910231.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  std = np.float64(a.iloc[:,2].to_numpy())
C:\Users\ashis\AppData\Local\Temp\ipykernel_14140\46910231.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  mean = np.float64(a.iloc[:,1].to_numpy())

In [31]:
pred_labels = label_generator(model.predict(tdf.to_numpy()))

In [32]:
pd.value_counts(pred_labels)

C:\Users\ashis\AppData\Local\Temp\ipykernel_14140\3154038371.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(pred_labels)
C:\Users\ashis\AppData\Local\Temp\ipykernel_14140\3154038371.py:1: FutureWarning: value_counts with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  pd.value_counts(pred_labels)

1    21963
0     3037
Name: count, dtype: int64

In [33]:
preddf = pd.DataFrame({'prediction' : pred_labels})
preddf.to_csv('val_binary.csv')